### ISSUE TITLE
Throw a better error when data can't be loaded

### ISSUE THREAD

**Issue by tgvashworth** [phuu/integrator-match#9]
Would useful to know:
- [x] What path was attempted
- [ ] JSON errors if there are any

**Comment by waltfy** [comment]
@phuu +1. 

43a755b now throws a more informative Error. Like:

`throw new Error(`ElementMatcher: Could not load Spec ${ key } from ${ SPEC_STORE._dir }`);`

`jfs` actually logs a `[SyntaxError error]`, which we don't actually have control over. Will leave issue open until we find a better way.

**Comment by waltfy** [comment]
As discussed offline. We will probably move away from `jfs` to just using `fs`, as it can read in JSON files easily, and we will have finer control over it.

See #11
